apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-linux-systemd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kali
  template:
    metadata:
      labels:
        app: kali
    spec:
      containers:
      - name: kali-container
        image: lostcauze7/kali-dockerized:latest
        ports:
        - containerPort: 8087
        securityContext:
          privileged: true
        workingDir: /usr
        command:
        - "bash"
        stdin: true
        tty: true